sudo: required
before_install:
  - export CONTAINER=$(find container* -type f -printf "%f")
  - echo $CONTAINER
  - export DROID=$(find DROID* -type f -printf "%f")
  - echo $DROID
  - echo $TRAVIS_BUILD_DIR
  - export JYTHON_URL='http://search.maven.org/remotecontent?filepath=org/python/jython-installer/2.7.0/jython-installer-2.7.0.jar'
  - export POI='3.17'
  - export POI_URL="http://www-us.apache.org/dist/poi/release/bin/poi-bin-$POI-20170915.tar.gz"
  - wget $JYTHON_URL -O jython_installer.jar; java -jar jython_installer.jar -s -d $HOME/jython; export PATH=$HOME/jython:$PATH
  - wget $POI_URL -O poi.tar.gz; tar -xvf poi.tar.gz
  - export CLASSPATH=$TRAVIS_BUILD_DIR/$POI/$POI.jar:$CLASSPATH
#  - wget -qO - https://bintray.com/user/downloadSubjectPublicKey?username=bintray | sudo apt-key add -
#  - echo "deb http://dl.bintray.com/siegfried/debian wheezy main" | sudo tee -a /etc/apt/sources.list
#  - sudo apt-get update && sudo apt-get install siegfried
  - git clone https://github.com/exponential-decay/skeleton-test-suite-generator.git $HOME/skeleton-test-suite-generator
  - git clone https://github.com/exponential-decay/skeleton-container-test-suite-generator.git $HOME/skeleton-container-test-suite-generator
script:
#  - roy harvest -home .
#  - mkdir -p $HOME/skeleton-test-suite-generator/pronom-export/{fmt,x-fmt}
#  - cp pronom/fmt* $HOME/skeleton-test-suite-generator/pronom-export/fmt/
#  - cp pronom/x-fmt* $HOME/skeleton-test-suite-generator/pronom-export/x-fmt/
#  - cd $HOME/skeleton-test-suite-generator
#  - python skeletongenerator.py
  - cd $HOME/skeleton-container-test-suite-generator
  - jython -Dpython.path=$CLASSPATH skeletoncontainergenerator.py --con $TRAVIS_BUILD_DIR/$CONTAINER --sig $TRAVIS_BUILD_DIR/$DROID
