sudo: required
before_install:
  - export JYTHON_URL='http://search.maven.org/remotecontent?filepath=org/python/jython-installer/2.7.0/jython-installer-2.7.0.jar'
  - export POI_URL='https://www.apache.org/dyn/closer.lua/poi/release/bin/poi-bin-3.17-20170915.tar.gz'
  - wget $JYTHON_URL -O jython_installer.jar; java -jar jython_installer.jar -s -d $HOME/jython; export PATH=$HOME/jython:$PATH
  - wget $POI_URL -O poi.tar.gz; 
  - wget -qO - https://bintray.com/user/downloadSubjectPublicKey?username=bintray | sudo apt-key add -
  - echo "deb http://dl.bintray.com/siegfried/debian wheezy main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update && sudo apt-get install siegfried
  - git clone https://github.com/exponential-decay/skeleton-test-suite-generator.git $HOME/skeleton-test-suite-generator
script:
  - roy harvest -home .
  - mkdir -p pronom-export/{fmt,x-fmt}
  - cp pronom/fmt* prononm-export/fmt/
  - cp pronom/x-fmt* pronom-export/x-fmt/
  - ls fmt
  - ls x-fmt
  - python $HOME/skeleton-test-suite-generator/skeletongenerator.py
