name: Builder
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "CONTAINER=$(find container* -type f -printf "%f")" >> $GITHUB_ENV
      - run: echo "DROID=$(find DROID* -type f -printf "%f")" >> $GITHUB_ENV
      - name: Install Jython
        run: wget $JYTHON_URL -O jython_installer.jar; java -jar jython_installer.jar -s -d $HOME/jython; export PATH=$HOME/jython/bin:$PATH
        env: 
          JYTHON_URL: 'http://search.maven.org/remotecontent?filepath=org/python/jython-installer/2.7.0/jython-installer-2.7.0.jar'
      - name: Install POI
        run: wget $URL -O poi.tar.gz; tar -xvf poi.tar.gz
        env: 
          URL: "https://archive.apache.org/dist/poi/release/bin/poi-bin-3.17-20170915.tar.gz"
      - run: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 20F802FE798E6857
      - run: sudo add-apt-repository "deb https://www.itforarchivists.com/ buster main"
      - run: sudo apt-get update && sudo apt-get install siegfried
      - run: git clone https://github.com/exponential-decay/skeleton-test-suite-generator.git $HOME/skeleton-test-suite-generator
      - run: git clone https://github.com/exponential-decay/skeleton-container-test-suite-generator.git $HOME/skeleton-container-test-suite-generator
      - run: roy harvest -home .
      - run: mkdir -p $HOME/output/skeleton-suite/containers
      - run: cp $GITHUB_WORKSPACE/$CONTAINER $HOME/output/
      - run: cp $GITHUB_WORKSPACE/$DROID $HOME/output/
      - run: cp -rf pronom $HOME/output/
      - run: mkdir -p $HOME/skeleton-test-suite-generator/pronom-export/{fmt,x-fmt}
      - run: cp pronom/fmt* $HOME/skeleton-test-suite-generator/pronom-export/fmt/
      - run: cp pronom/x-fmt* $HOME/skeleton-test-suite-generator/pronom-export/x-fmt/
      - run: cd $HOME/skeleton-test-suite-generator
      - run: python skeletongenerator.py
      - run: cd skeleton-suite
      - run: cp -rf fmt $HOME/output/skeleton-suite/
      - run: cp -rf x-fmt $HOME/output/skeleton-suite/
      - run: cd $HOME/skeleton-container-test-suite-generator
      - run: jython -Dpython.path=$poi-3.17/poi-3.17.jar skeletoncontainergenerator.py --con $TRAVIS_BUILD_DIR/$CONTAINER --sig $TRAVIS_BUILD_DIR/$DROID
      - run: cp skeleton-container-suite/zip/* $HOME/output/skeleton-suite/containers/
      - run: cp skeleton-container-suite/ole2/* $HOME/output/skeleton-suite/containers/
      - run: cd $HOME/output
      - run: zip -r $HOME/pronom.zip . 